service: alexa-skills

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  region: us-east-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  winner:
    handler: bin/winner
    environment:
      REDIS_HOST: 10.0.1.36
      REDIS_PORT: 6379
    events:
      - alexaSkill: amzn1.ask.skill.fbcb2d8f-676a-4db8-8d1f-9e48285b59af
      - schedule:
          rate: rate(5 minutes)
          input: '{"version": "1.0","context": {"System": {"device": {"supportedInterfaces": {}},"apiEndpoint": "https://api.amazonalexa.com"}},"request": {"type": "IntentRequest","intent": {"name": "WinnerIntent","confirmationStatus": "NONE"}}}'
    vpc:
      securityGroupIds:
        - sg-07d2cfe6397215f93
      subnetIds:
        - subnet-05805aef1e51270a7
        - subnet-010a474d64ae6d13b
        - subnet-01c79fd6cc62e267b
  deletekeys:
    handler: bin/deletekeys
    environment:
      REDIS_HOST: 10.0.1.36
      REDIS_PORT: 6379
    events:
      - alexaSkill: amzn1.ask.skill.fa7f7487-a810-41b5-9963-05aea4c6554d
      - schedule:
          rate: rate(5 minutes)
          input: '{"version": "1.0","context": {"System": {"device": {"supportedInterfaces": {}},"apiEndpoint": "https://api.amazonalexa.com"}},"request": {"type": "IntentRequest","intent": {"name": "DeleteKeysIntent","confirmationStatus": "NONE"}}}'
    vpc:
      securityGroupIds:
        - sg-07d2cfe6397215f93
      subnetIds:
        - subnet-05805aef1e51270a7
        - subnet-010a474d64ae6d13b
        - subnet-01c79fd6cc62e267b
